apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-app
  name: dinipere-pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-app
    spec:
      containers:
        - image: nginx:latest
          name: prod-con
          ports:
            - containerPort: 80
